require_relative "../spec_helper"
require_relative '../../lib/star_fetcher'

describe StarFetcher do
  it "creates a file with a user's stars" do
    github_username = "anhari"

    expect(StarFetcher.fetch_stars_for_user(user: github_username)).to eq %w[
      lokesh/lightbox2
      jonathanslenders/ptpython
      lpil/dogma
      spratt/Computer-Modern
      AndrewRadev/vimrunner
      GeekyAnts/react-native-easy-grid
      gregs1104/pgtune
      stavro/arc
      elixirkoans/elixir-koans
      christoomey/vim-rfactory
      thoughtbot/json_matchers
      ohler55/oj
      csscomb/vim-csscomb
      christoomey/vim-system-copy
      christoomey/vim-sort-motion
      vim-scripts/ReplaceWithRegister
      tommcdo/vim-exchange
      you-dont-need/You-Dont-Need-JavaScript
      thoughtbot/fake_stripe
      turingschool/curriculum
      turingschool/backend-curriculum-site
      turingschool/career-development-curriculum
      turingschool/front-end-curriculum
      posquit0/Awesome-CV
      jtushman/pivotal_tools
      pivotal/gumshoe
      zplug/zplug
      jostmey/NakedTensor
      kdn251/interviews
      donnemartin/interactive-coding-challenges
      donnemartin/data-science-ipython-notebooks
      donnemartin/dev-setup
      donnemartin/gitsome
      donnemartin/system-design-primer
      kollegorna/rspec-api_helpers
      szw/vim-g
      hnarayanan/shpotify
      eduarbo/chrome-devtools-gruvbox-dark-theme
      matze/vim-move
      ismay/dotfiles
      sergiotapia/magnetissimo
      thechangelog/changelog.com
      ValveSoftware/Dota-2
      junegunn/vim-github-dashboard
      junegunn/myvim
      junegunn/vim-emoji
      junegunn/gv.vim
      brzpegasus/ember-cli-nwjs
      martndemus/ember-form-for
      vt-elixir/ja_resource
      AndrewRadev/splitjoin.vim
      AndrewRadev/ember_tools.vim
      herrbischoff/awesome-osx-command-line
      morhetz/gruvbox
      vim-scripts/AfterColors.vim
      neomake/neomake
      knownasilya/ember-named-yields
      markerikson/react-redux-links
      ninenines/cowboy
      phoenixframework/phoenix_html
      elixir-ecto/ecto
      elixir-lang/plug
      danmcclain/voorhees
      vt-elixir/ja_serializer
      apolzon/ember-cli-refills-components
      softlayer/sl-ember-components
      sorrycc/awesome-javascript
      nmec/awesome-ember
      markets/awesome-ruby
      DockYard/styleguides
      ember-cli/ember-cli-eslint
      DockYard/eslint-plugin-ember-suave
      DockYard/ember-changeset-validations
      DockYard/ember-changeset
      pangloss/vim-javascript
      StephenGrider/ElixirCode
      christoomey/dotfiles
      junegunn/fzf.vim
      phoenixframework/phoenix
      chrismccord/phoenix_chat_example
      dnl-blkv/mcdowell-cv
      sheerun/vim-polyglot
      jekyll/jekyll
      ember-cli/ember-cli
      emberjs/ember.js
      tmuxinator/tmuxinator
      junegunn/fzf
      dsawardekar/ember.vim
      DockYard/ember-route-action-helper
      DockYard/ember-one-way-controls
      ebryn/ember-component-css
      calderalabs/rspec_api_blueprint
      toddmotto/public-apis
      marmelab/awesome-rest
      alexlafroscia/vim-ember-cli
      JarrodCTaylor/vim-ember-cli-test-runner
      piotrmurach/tty
      vimperator/vimperator-labs
      tpope/gem-shut-the-fuck-up
      ember-redux/ember-redux
      NYTimes/kyt
      allinurl/goaccess
      elixir-lang/mime
      webmachine/webmachine
      thoughtbot/bamboo
      weiweihuanghuang/Work-Sans
      elixir-lang/elixir
      erlang/otp
      elli-lib/elli
      fvsch/remarkdown
      christopheradams/elixir_style_guide
      sarabander/sicp-pdf
      cerebris/jsonapi-resources
      thoughtbot/gitsh
      ember-cli/ember-cli-mocha
      emberjs/ember-mocha
      ember-weekend/ember-weekend-api
      smoku/phoenix_api_docs
      google/material-design-icons
      facebookincubator/create-react-app
      necolas/normalize.css
      OscarGodson/EpicEditor
      typeplate/typeplate.github.io
      guillaumepotier/Parsley.js
      thoughtbot/bourbon
      chartjs/Chart.js
      heelhook/chardin.js
      ubuwaits/beautiful-web-type
      WickyNilliams/headroom.js
      moment/moment
      erikflowers/weather-icons
      thoughtbot/bitters
      IanLunn/Hover
      kenwheeler/slick
      cferdinandi/smooth-scroll
      thoughtbot/refills
      thoughtbot/sky-labels
      PharkMillups/beautiful-docs
      codrops/HoverEffectIdeas
      thoughtbot/design-sprint
      willianjusten/awesome-svg
      sketchplugins/plugin-directory
      dimsemenov/PhotoSwipe
      fat/zoom.js
      zenorocha/clipboard.js
      JohnCoates/Aerial
      jlevy/the-art-of-command-line
      HubSpot/tether
      joshbuchea/HEAD
      FezVrasta/popper.js
      Selz/plyr
      philipwalton/html-inspector
      nosir/cleave.js
      callmecavs/jump.js
      brunopulis/awesome-a11y
      Famolus/awesome-sass
      LukyVj/accecss
      kylef/apiblueprint.vim
      dnuux/dotfiles
      bitemyapp/learnhaskell
      qrpike/Web-Font-Load
      treyhunner/resume
      poetic/ember-cli-github-pages
      jekyll/jekyll-compose
      thoughtbot/proteus-middleman
      amkirwan/ember-oauth2
      discourse/discourse
      tpope/vim-ragtag
      lukehoban/es6features
      thoughtbot/constable
      roots/sage
      janko-m/vim-test
      sger/ElixirBooks
      getify/You-Dont-Know-JS
      thoughtbot/trail-map
      DMarby/unsplash-downloader
      elabs/pundit
      h4cc/awesome-elixir
      guarinogabriel/Mac-CLI
      stefanRitter/flux-rails-assets
      zethussuen/epic-editor-rails
      thoughtbot/ember-cli-rails
      djoshea/vim-autoread
      enaqx/awesome-react
      facebook/react
      storybooks/react-storybook
      ericdouglas/ES6-Learning
      gregnavis/active_record_doctor
      scotttball/react_rails_twitter_knockoff
      applegrain/creact
      cmdrkeene/memegen
      bensmithett/sample-react-rails-app
      reactjs/react-tutorial
      kucaahbe/rspec-html-matchers
      graysonwright/money
      tpope/vim-bundler
      christoomey/vim-conflicted
      jgdavey/vim-blockle
      thoughtbot/foundry
      tpope/vim-rails
      manosim/gitify
      acarapetis/vim-colors-github
      preston/railroady
      ianheggie/rbenv-binstubs
      rodreegez/powder
      ReactTraining/react-fundamentals-curriculum
      ReactTraining/React-Fundamentals
      reactjs/react-rails
      ai/autoprefixer-rails
      collectiveidea/delayed_job
      sickill/vim-pasta
      IcaliaLabs/kaishi
      thoughtbot/clearance
      thoughtbot/shoulda-matchers
      beloglazov/vim-online-thesaurus
      thoughtbot/dotfiles
      joshdick/onedark.vim
      freeCodeCamp/freeCodeCamp
      mathiasbynens/dotfiles
      christoomey/vim-tmux-runner
      haml/html2haml
      hlissner/vim-ultisnips-snippets
      honza/vim-snippets
      thoughtbot/griddler
      thoughtbot/laptop
      thoughtbot/guides
      stephenb/sendgrid
      thoughtbot/proteus
      thoughtbot/high_voltage
      oddbird/susy
      zenorocha/browser-diet
      zenorocha/alfred-workflows
      ankane/groupdate
      ankane/chartkick
      hothero/awesome-rails-gem
      bengrunfeld/bootstrap-grid-ai
      thoughtbot/rcm
      rking/ag.vim
      ggreer/the_silver_searcher
      connermcd/notes
      connermcd/dotfiles
      erikw/tmux-powerline
      monfresh/laptop
      pry/pry
      north/north
      afshinator/OdinRailsStudyGroup
      matthewrobertson/ERB-Sublime-Snippets
      Xuyuanp/nerdtree-git-plugin
      rizzatti/dash.vim
      scrooloose/nerdtree
      junegunn/vim-plug
      thoughtbot/suspenders
      tiimgreen/github-cheat-sheet
      vsouza/awesome-ios
      matteocrippa/awesome-swift
    ]
  end
end
